config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('mysite.accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

sandbox/customauth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from sandbox.customauth.views import IndexView
from sandbox.customauth.forms import EmailAuthenticationForm

app_name = 'customauth'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
            template_name='customauth/login.html',
            form_class=EmailAuthenticationForm
        ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('customauth/password_reset/', auth_views.PasswordResetView.as_view(
            template_name='customauth/password_reset.html',
            email_template_name='customauth/password_reset_email.html',
            subject_template_name='customauth/password_reset_subject.txt',
            success_url=reverse_lazy('customauth:password_reset_done')
        ), name='password_reset'),
    path('customauth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='customauth/password_reset_done.html'
        ), name='password_reset_done'),
    path('customauth/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='customauth/password_reset_confirm.html',
            success_url=reverse_lazy('customauth:password_reset_complete')
        ), name='password_reset_confirm'),
    path('customauth/reset/done/', auth_views.PasswordResetCompleteView.as_view(
            template_name='customauth/password_reset_complete.html'
        ), name='password_reset_complete'),

    path('', IndexView.as_view(), name='index'),
]

sandbox/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('', include('sandbox.customauth.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

sandbox/customauth/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    email = models.EmailField(
        _('email address'),
        unique=True,
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    full_name = models.CharField(_('full name'), max_length=50, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

sandbox/customauth/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class EmailAuthenticationForm(forms.Form):
    """
    Class for authenticating users.
    """
    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(email)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "email" field.
        self.email_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.
        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.
        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'email': self.email_field.verbose_name},
        )

sandbox/customauth/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'customauth/index.html'

sandbox/customauth/templates/customauth/index.html
you're logged in.

sandbox/customauth/templates/customauth/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-5-tablet is-4-desktop is-3-widescreen">
    <form method="post" action="{% url 'customauth:login' %}" class="box">
      {% csrf_token %}

      {% if form.errors %}
      <article class="message is-danger">
        <div class="message-body">
          Your email and password didn't match. Please try again.
        </div>
      </article>
      {% endif %}

      <div class="field">
        <div class="control has-icons-left">
          <input type="email" placeholder="Email" class="input" name="email" value="{{ form.email.value|default:'' }}" required>
          <span class="icon is-small is-left">
            <i class="fa fa-envelope"></i>
          </span>
        </div>
      </div>
      <div class="field">
        <div class="control has-icons-left">
          <input type="password" placeholder="Password" class="input" name="password" value="{{ form.password.value|default:'' }}" required>
          <span class="icon is-small is-left">
            <i class="fa fa-lock"></i>
          </span>
        </div>
      </div>
      <div class="field">
        <a class="is-size-7" href="{% url 'customauth:password_reset' %}">Forgot password?</a>
      </div>
      <div class="field">
        <div class="control">
          <button class="button is-primary is-fullwidth">Login</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

sandbox/customauth/templates/customauth/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-7-tablet is-6-desktop is-5-widescreen">
    <form method="post" class="box">
      {% csrf_token %}

      <div class="field">
        <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
      </div>

      <hr>

      <div class="field">
        <label class="label is-small">Login email address</label>
        <div class="control">
          <input type="email" placeholder="Email" class="input" name="email" value="{{ form.email.value|default:'' }}" required>
        </div>
        {% if form.errors.email %}
          {% for message in form.errors.email %}
            <p class="help is-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}
      </div>
      <div class="field">
        <div class="control">
          <button class="button is-primary is-fullwidth">Continue</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

sandbox/customauth/templates/customauth/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-7-tablet is-6-desktop is-5-widescreen">
    <div class="box">
      <p>Your password has been set.  You may go ahead and log in now.</p>
      <br>
      <a href="{% url 'customauth:login' %}">Log in</a>
    </div>
  </div>
</div>
{% endblock %}

sandbox/customauth/templates/customauth/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Password reset confirmation{% endblock %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-5-tablet is-4-desktop is-3-widescreen">
    <form method="post" class="box">
      {% csrf_token %}

      <div class="field">
        <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
      </div>

      <hr>

      <div class="field">
        <label class="label is-small">New password</label>
        <div class="control">
          <input type="password" class="input" name="new_password1" required>
        </div>
        {% if form.errors.new_password1 %}
          {% for message in form.errors.new_password1 %}
            <p class="help is-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}
      </div>

      <div class="field">
        <label class="label is-small">Confirm password</label>
        <div class="control">
          <input type="password" class="input" name="new_password2" required>
        </div>
        {% if form.errors.new_password2 %}
          {% for message in form.errors.new_password2 %}
            <p class="help is-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}
      </div>

      <div class="field">
        <div class="control">
          <button class="button is-primary is-fullwidth">Continue</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

sandbox/customauth/templates/customauth/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password reset sent{% endblock %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-7-tablet is-6-desktop is-5-widescreen">
    <div class="box">
      <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
      <br>
      <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
    </div>
  </div>
</div>
{% endblock %}

sandbox/customauth/templates/customauth/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'customauth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}